### ISSUE TITLE
Allow other Linux Destros to take place of bash

### ISSUE THREAD

**Issue by aps120797** [Microsoft/WSL-DistroLauncher#25]
I am not sure if this issue needs to be opened here or at [Microsoft/vscode](https://github.com/Microsoft/vscode). 
But, it appears that currently, WSL prefers Ubuntu only to be it's primary WSL Bash terminal. (I already have [Ubuntu ](https://www.microsoft.com/en-in/store/p/ubuntu/9nblggh4msv6), [openSUSE Leap 42](https://www.microsoft.com/en-in/store/p/opensuse-leap-42/9njvjts82tjx), [Debian GNU/Linux ](https://www.microsoft.com/en-in/store/p/debian-gnu-linux/9msvkqc78pk6) and [Kali Linux](https://www.microsoft.com/store/productId/9PKR34TNCV07).

Here's a screenshot of for the same on VS Code:
![capture](https://user-images.githubusercontent.com/20141002/37964045-c57efa0e-31dd-11e8-9460-a5c9ebf1c442.PNG)

I think, the same follows for other code editors with integrated terminals. (See path for WSL in the above image).

Please do let me know, if this is a VS Code only problem, so that I will reference this issue there, or it's related to some other repository. Also, I am currently on Microsoft Windows Version 1709 (Fall Creators Update)  with OS Build 16299.334.

**Comment by Biswa96** [comment]
Try to change the default distribution with `wslconfig /s <distro_name>` command. Also you can change the executable name in settings manually.

**Comment by aps120797** [comment]
Thanks. It worked! 😄
