### ISSUE TITLE
Generate on Linux

### ISSUE THREAD

**Issue by piranna** [microsoft/WSL-DistroLauncher#32]
Provide instructions to allow to generate the distro .tar.gz file from a Linux host machine.

**Comment by Biswa96** [comment]
That somehow depends on the Linux distributions you want to install. For example, here is the shell script to make Kali Linux .tar.gz file: https://github.com/offensive-security/Kali-WSL-chroot/blob/master/build_chroot.sh

**Comment by piranna** [comment]
Cool! :-D Yes, I was looking for something similar to automate creation of [NodeOS](http://node-os.com/) images :-)

**Comment by Biswa96** [comment]
I think we should discuss this on your repository.

**Comment by benhillis** [comment]
The tar.bz can be generated in a variety of ways.  Many distributions will already generate one as part of their docker / cloud targeted SKUs. The only limitation is that it must contain the root file system in a top level directory.  I'll add some instructions to the readme, but for example you could tar up an existing Linux install by using:

`sudo /bin/bash -c "cd / ; tar -cpzf /install.tar.gz --exclude=/install.tar.gz --one-file-system /"`

Note this will include lots of things that aren't needed for wsl (like the /boot directory).

**Comment by oiaohm** [comment]
Really this is big question.  Since tar.gz are needed for docker images and other things.   Why not have a generic installer and why not be able to use those images with maybe a few extra files.

This would allow distributions to save on resources.

**Comment by gbraad** [comment]
It depends on the distro how to make this, for Fedora we used:
https://gitlab.com/gbraad/fedora-wsl
Note: however, taking a docker image as root filesystem will also usually
work.

**Comment by rhaist** [comment]
You can have a look at the file I used for Debian WSL here:

https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh
