### ISSUE TITLE
Publishing to store

### ISSUE THREAD

**Issue by agowa338** [Microsoft/WSL-DistroLauncher#40]
How do I get the necessary rights to publish a WSL app?
If I upload it, I just get the following Error message:
```
Package acceptance validation error: You don't have permissions to specify the following namespaces in the appx manifest file of the package DistroLauncher-Appx_1.0.1.0_x64.appx: restricted namespace: http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities
```
If I follow the link, I get 
```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

Can you please include necessary steps on the Wiki Page "Notes for uploading to the Store"?
Also a note that registration to "Desktop Bridge" is required would have been nice.
Link: https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge
```
Package acceptance validation error: Your developer account doesn’t have permission to submit apps converted with the Desktop Bridge at this time. https://aka.ms/desktopbridgeforwindowsstore
```

**Comment by Biswa96** [comment]
You've to register a name for your Appx package in Windows Store and 19$ to register with MS account. Also edit the AppxManifest.xml file. You also need permission of that GNU/Linux distribution owner.

**Comment by DarthSpock** [comment]
I do believe that Linux distro maintainers will get a free account. At least that was my understanding. Whether that's through re-imbursement or some other method, I'm not entirely sure. @tara-raj or @bitcrazed should be address this more thoroughly. Alternatively @rhaist and @offensive-security have already gone through the process and should be able to provide some pointers.

**Comment by DarthSpock** [comment]
Oh and also at the bottom of the repo page: 

> You may also reach out to our team alias at wslpartners@microsoft.com for questions related to submitting your app to the Microsoft Store.

**Comment by tara-raj** [comment]
Yes, please reach out to the email @DarthSpock listed above. You need special permissions to submit this type of app to the Store which requires approval by a product group member (aka me).

**Comment by agowa338** [comment]
A few seconds ago I sent an E-Mail to your team. Still I would appreciate a publicly available documentation of the whole workflow, so that even unexperienced/new Store publishers know how to get there stuff in and what time they have to expect.

**Comment by tara-raj** [comment]
Created a new issue to update the documentation - https://github.com/Microsoft/WSL-DistroLauncher/issues/41
