### ISSUE TITLE
What Ubuntu rootfs to use?

### ISSUE THREAD

**Issue by bbrala** [Microsoft/WSL-DistroLauncher#53]
I really want to build my own package for development. But i can't figure out what rootfs is used. Is the code to generate the correct rootfs somewhere? I tried using the ubuntu cloudimg rootfs's which are hosted [on canonical.com](https://partner-images.canonical.com/core/xenial/current/) but that doesn't work :(

Anyone have any idea?

**Comment by rhaist** [comment]
Hey @bbrala - just build a rootfs with debootstrap or cdebootstrap.

You can have a look at my script:
https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh

**Comment by bbrala** [comment]
Yeah i kinda tried that but with multistrap. But from what i seem to gather something like the following should work fine.

https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-root.tar.gz

So perhaps it is my build which is not correct... When i run the built exe it just opens and closes at once.  I did your project and had a look at it to see if there is something i was doing wrong. I think i'll try and build that before i try and rebuild with a changed rootfs.

**Comment by bbrala** [comment]
Ok, appearantly i had to build in VS with Project -> Store -> Create App packages and select sideload. This seems to work fine. Next i will just `chroot` in the filesystem and start adding the packages i need, think this will work out yay :)

**Comment by bbrala** [comment]
I ended up using docker to build the root fs and exporting it for use in our custom built distribution for developemnt.
