### ISSUE TITLE
Package.StoreAssociation.xml can't be generated

### ISSUE THREAD

**Issue by khuevu** [Microsoft/WSL-DistroLauncher#54]
Hi, 
When I tried to build the project using build.bat, I got the error:
`Could not find file ... DistroLauncher-Appx\Package.StoreAssociation.xml`. 

I tried to create one by selecting Store > Associate App with the Store .. but then it gave me this error: 

"Unable to associate your App with the Window Store because the app manifest is invalid. Correct the errors in the app manifest.". 

I am running Window 10, Visual Studio P. 2017 - 15.9.3
Please help . Thank you

**Comment by benhillis** [comment]
Have you checked the errors in the app manifest?

**Comment by khuevu** [comment]
@benhillis : Yes, it says this line not valid: https://github.com/Microsoft/WSL-DistroLauncher/blob/master/DistroLauncher-Appx/MyDistro.appxmanifest#L14
because no Capability element in rescap namespace. I tried to change it to something valid like `<Capability Name="internetClient" /> as in https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/how-to-specify-capabilities-in-a-package-manifest . After that the editor doesn't complaint anymore but it still gives me the same error when associating store

**Comment by benhillis** [comment]
Interesting, I did not see that locally. I will give this a try.

**Comment by khuevu** [comment]
@benhillis it turns out that the error was because Visual Studio's C++ plugin for window universal app weren't installed for me. After installing it, I can see the wizard for associate the store but I encounter another unhelpful error: "An unexpected error occurred when attempting to reserve the app name". I have tried many different names including random names . I can't tell much from the error. You have any suggestion?

**Comment by khuevu** [comment]
I think it was because of the way I generated the cert. I tried generating the test cert manually instead of using Visual Studio utility. Will close this now. I only wish that the error message had been more informative.
