### ISSUE TITLE
Stuck adding my distro to WSL, don't know how to debug or where to find logs

### ISSUE THREAD

**Issue by marler8997** [Microsoft/WSL-DistroLauncher#57]
I'm trying to get my custom linux distro to run in WSL.  I'm able to register it but cannot run anything in it.  From what I've learned from experimentation and looking at some launcher code, when you call `WslRegisterDistribution`, WSL seems to determines the "distro folder" based on the path where the running executable is stored, then takes the rootfs file given as the second argument and extracts it to the folder.  It then makes some registry entries in:

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss`

with the Name/BasePath etc.  I can verify my distro is registerd with `wslconfig /l` (looks like my Windows 10 isn't the most up-to-date) and I can see it in the registry.

When I try to launch my distro, either by invoking`WslLaunchInteractive` from an executable or by running `wsl -d mydistro run`, it just exits immediately with no message as to what went wrong.  The `WslLaunchInteractive` function returns 0 (success) and sets the exit code to `-1`.  I've tried running different binaries from my distro but still see the same result.  At this point I'm not sure what to do as I don't have access to the `WslLaunchInteractive` source code and I don't know where to find error logs.  Are there error logs somewhere?  Is there a way to enable more logging or triage what's going wrong?  Maybe my distro is missing some file in it, is there documentation on what WSL requires from a distro's rootfs that I could be missing? (by the way, I tried adding `/etc/wslpath` as I noticed that Alpine seems to have this file and set it to my distro's `/sbin/init` process, and also, Alpine and Ubuntu 16.04 work just fine).  Any help is appreciated, thanks!

My distro source is here: https://github.com/marler8997/maros
I've written some wsl tools to help me here: https://github.com/marler8997/wsl-launcher

**Comment by Biswa96** [comment]
Could you provide a tar.gz file link of your distro?

**Comment by marler8997** [comment]
Sure: https://github.com/marler8997/maros/releases/tag/ForTest

**Comment by Biswa96** [comment]
Try this:
1. Make `passwd` file with `touch /etc/passwd`.
2. Add this line `root:x:0:0:root:/:/bin/msh` in that file.
3. Move `/sbin/msh` (your shell) to `/bin/msh`. Or you can make a symbolic link but it may be complex to do.
4. Pack in `tar.gz` file only.

HTH :)

**Comment by marler8997** [comment]
Thanks for the help! Are these requirements documented somewhere?

**Comment by marler8997** [comment]
That did the trick! I'm now able to launch my distro with `wsl -d mydistro`.
