### ISSUE TITLE
生产appx文件失败

### ISSUE THREAD

**Issue by guanzi008** [microsoft/WSL-DistroLauncher#59]
正在移除目录“x64\Debug\DistroLauncher-Appx_1.0.3.0_Bundle\”。
         正在创建目录“x64\Debug\DistroLauncher-Appx_1.0.3.0_Bundle”。
         创建硬链接以将“D:\wsl\WSL-DistroLauncher-master\x64\Debug\DistroLauncher-Appx\DistroLauncher-Appx_1.0.3.0_x64_Debug.msix”复制到“x64\Debug\DistroLauncher-Appx_1.0.3.0_
         Bundle\DistroLauncher-Appx_1.0.3.0_x64_Debug.msix”。
         Adding file 'x64\Debug\DistroLauncher-Appx_1.0.3.0_Bundle\DistroLauncher-Appx_1.0.3.0_x64_Debug.msix'
         C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\MakeAppx.exe bundle /d x64\Debug\DistroLauncher-Appx_1.0.3.0_Bundle\ /bv 1.0.3.0 /o /p D:\wsl\WS
         L-DistroLauncher-master\AppPackages\DistroLauncher-Appx\DistroLauncher-Appx_1.0.3.0_Debug_Test\DistroLauncher-Appx_1.0.3.0_x64_Debug.msixbundle
     4>MakeAppx : error : Error info: ?????? [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]
     4>MakeAppx : error : Bundle creation failed. [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]
     4>MakeAppx : error : 0x80080215 - ????????????????? appx ???? [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]
     4>已完成生成项目“D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj”(默认目标)的操作 - 失败。
     3>已完成生成项目“D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj.metaproj”(默认目标)的操作 - 失败。
     1>已完成生成项目“D:\wsl\WSL-DistroLauncher-master\DistroLauncher.sln”(Build 个目标)的操作 - 失败。

生成失败。

       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher.sln”(Build 目标) (1) ->
       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj.metaproj”(默认目标) (3) ->
       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj”(默认目标) (4) ->
       (PrepareForBuild 目标) ->
         D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(452,5): warning MSB8028: The intermediate
        directory (x64\Debug\) contains files shared from another project (mydistro.vcxproj).  This can lead to incorrect clean and rebuild behavior. [D:\wsl\WSL-Dis
       troLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]

       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher.sln”(Build 目标) (1) ->
       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj.metaproj”(默认目标) (3) ->
       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj”(默认目标) (4) ->
       (_ValidateAppxManifest 目标) ->
         MyDistro.appxmanifest(14,6): warning APPX0006: 此项目使用“runFullTrust”功能。应使用 Windows 应用程序打包项目来生成存储和旁加载程序包。有关详细信息，请参阅 https://go.microsoft.com/fwlink/?linkid=871
       803。 [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]

       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher.sln”(Build 目标) (1) ->
       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj.metaproj”(默认目标) (3) ->
       “D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj”(默认目标) (4) ->
       (_CreateBundle 目标) ->
         MakeAppx : error : Error info: ?????? [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]
         MakeAppx : error : Bundle creation failed. [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]
         MakeAppx : error : 0x80080215 - ????????????????? appx ???? [D:\wsl\WSL-DistroLauncher-master\DistroLauncher-Appx\DistroLauncher-Appx.vcxproj]

    2 个警告
    3 个错误

已用时间 00:00:22.53
C:\Users\d>

**Comment by KsRyY** [comment]
你有安装对应版本的Win10SDK吗？

**Comment by guanzi008** [comment]
我已经解决了，就是SDK问题，代码里有一个SDK版本没有修改，(我修改需要文本打开那个文件修改。成最新的就编译成功了。)然而我用的最新的SDK没有安装指定的SDK版本。



---原始邮件---
发件人: "Andy Chen"<notifications@github.com>
发送时间: 2019年8月7日(星期三) 晚上10:27
收件人: "microsoft/WSL-DistroLauncher"<WSL-DistroLauncher@noreply.github.com>;
抄送: "guanzi008"<245205080@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/WSL-DistroLauncher] 生产appx文件失败 (#59)



你有安装对应版本的Win10SDK吗？

**Comment by guanzi008** [comment]
。。。



---原始邮件---
发件人: "Ben Hillis"<notifications@github.com>
发送时间: 2019年8月8日(星期四) 凌晨0:49
收件人: "microsoft/WSL-DistroLauncher"<WSL-DistroLauncher@noreply.github.com>;
抄送: "guanzi008"<245205080@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/WSL-DistroLauncher] 生产appx文件失败 (#59)



Closed #59.

**Comment by benhillis** [comment]
I'm sorry for issues to be actionable I have to be able to read them... Could you please file your issue in English?

**Comment by KsRyY** [comment]
This problem is caused by incorrect Windows 10 SDK Version

**Comment by KsRyY** [comment]
Already solved
