### ISSUE TITLE
Creating a Redhat Distro?

### ISSUE THREAD

**Issue by harperjohn** [microsoft/WSL-DistroLauncher#63]
I realize that this not necessarily an "issue", but the information seems impossible to find.

I was on the Microsoft site and it looks like someone suggested creating a WSL forum, but it was decided to keep the discussion at Github... so I figured that I would try asking here...

Thanks in advance for your help (and possibly patience) :)

**Comment by benhillis** [comment]
I would suggest downloading a tarball that contains the redhat user space binaries and importing the distribution via wsl.exe --import
