### ISSUE TITLE
Custom Distro CI/CD build using github workflow

### ISSUE THREAD

**Issue by srbala** [microsoft/WSL-DistroLauncher#95]
Team this is more of question/requesting recommendation, might turn into a feature.

I am a SIG/Cloud member of AlmaLinux, looking to setup and automate build for `AlmaLinux-WSL` package. Is it possible to make use of github workflow to create `WSL` application package `(appx)`. Steps or sample would greatly appreciated.

I understand `AlmaLinux` team has to contact WSL team `wslpartners@microsoft.com` for initial setup AlmaLinux distro.

**Comment by KexyBiscuit** [comment]
You may look at [the workflow for AOSC OS](https://github.com/AOSC-Dev/AOSCOSLauncher/blob/main/.github/workflows/msbuild.yml), though the workflow artifacts are different from the one we publish to Microsoft Store. We always use Visual Studio on-premises to do that.
